# Generated by Django 5.1.2 on 2024-10-17 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_avatar_customuser_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("synopsis", models.TextField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Anime", "Anime"),
                            ("Action", "Action"),
                            ("Drame", "Drame"),
                            ("Comédie", "Comédie"),
                            ("Horreur", "Horreur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_sortie", models.DateField()),
                ("duree", models.PositiveIntegerField()),
                ("casting", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="film/")),
                (
                    "ntmoy",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
