# Generated by Django 5.1.2 on 2024-10-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_film"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=30, null=True)),
                ("prenom", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="acteur/"),
                ),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="film",
            name="casting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.acteur",
            ),
        ),
    ]
