# Generated by Django 5.1.2 on 2024-10-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_acteur_alter_film_casting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="casting",
        ),
        migrations.DeleteModel(
            name="Acteur",
        ),
        migrations.DeleteModel(
            name="Film",
        ),
    ]
