# Generated by Django 5.1.2 on 2024-10-17 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=30, null=True)),
                ("prenom", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="acteur/"),
                ),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("synopsis", models.TextField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Anime", "Anime"),
                            ("Action", "Action"),
                            ("Drame", "Drame"),
                            ("Comédie", "Comédie"),
                            ("Horreur", "Horreur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_sortie", models.DateField()),
                ("duree", models.PositiveIntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="film/")),
                (
                    "ntmoy",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "casting",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movie.acteur",
                    ),
                ),
            ],
        ),
    ]
