# Generated by Django 5.1.2 on 2024-10-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_critique_created_at_alter_critique_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="films",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="movie.film"
            ),
        ),
    ]
