# Generated by Django 5.1.2 on 2024-10-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_remove_comment_films"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="films",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="movie.film"
            ),
        ),
    ]
