# Generated by Django 5.1.2 on 2024-10-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_comment_films"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="films",
        ),
    ]
